slateci/slate-catalog-stable

charts/cms-xcache/.helmignore
charts/cms-xcache/Chart.yaml
charts/cms-xcache/README.md
charts/cms-xcache/templates/_helpers.tpl
charts/cms-xcache/templates/configmap.yaml
charts/cms-xcache/templates/deployment.yaml
charts/cms-xcache/templates/service.yaml
charts/cms-xcache/values.yaml

Initial commit of cms-xcache chart from stable.

---

.github/workflows/chart-lint.yaml
.github/workflows/release.yaml
README.md
chart_schema.yaml
ct.yaml
lintconf.yaml

Round of changes from incubator repo.

---

.dockerignore
.github/workflows/chart-lint.yaml
Dockerfile
README.md

Added docs and Dockerfile for local linting of charts.

---

charts/osg-frontier-squid/Chart.yaml
charts/osg-frontier-squid/README.md
charts/osg-frontier-squid/templates/NOTES.txt
charts/osg-frontier-squid/templates/_helpers.tpl
charts/osg-frontier-squid/templates/configmap.yaml
charts/osg-frontier-squid/templates/deployment.yaml
charts/osg-frontier-squid/templates/pvc.yaml
charts/osg-frontier-squid/templates/service.yaml
charts/osg-frontier-squid/values.yaml

Added osg-frontier-squid from current stable catalog.

---

.github/workflows/release.yaml

Updated release.yaml to reflect reusable github workflow changes.

---

.github/workflows/notify-api.yml
.github/workflows/release.yaml

New notify-api.yml github workflow.

---

charts/nginx/Chart.yaml

Bump version 1.2.2

---

.github/workflows/notify-api.yml
.github/workflows/pr.yaml
.github/workflows/release.yaml

Now using tags for reusable github workflow calls.

---

.github/workflows/release.yaml

Added slack notifications to release.yaml github workflow.

---

.github/workflows/notify-api.yml
.github/workflows/pr.yaml
.github/workflows/release.yaml

Updated slateci/github-action refs to @v9.

---

charts/nginx/Chart.yaml

47 complete stable app migration nginx

---

.github/workflows/notify-api.yml

Feature/58 update notify apiyml GitHub

---

charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/deployment.yaml
charts/osg-hosted-ce/templates/service.yaml
charts/osg-hosted-ce/values.yaml

Content sync from old stable catalog.

---

charts/perfsonar-testpoint/Chart.yaml
charts/perfsonar-testpoint/README.md
charts/perfsonar-testpoint/templates/_helpers.tpl
charts/perfsonar-testpoint/templates/deployment.yaml
charts/perfsonar-testpoint/values.yaml

50 complete stable app migration perfsonar testpoint

---

charts/faucet/Chart.yaml
charts/faucet/README.md
charts/faucet/templates/_helpers.tpl
charts/faucet/templates/configmap.yaml
charts/faucet/templates/deployment.yaml
charts/faucet/templates/pvc.yaml
charts/faucet/templates/service.yaml
charts/faucet/values.yaml

Closes #40
See #40 for more info

migrate faucet content

---

charts/grnoc-telegraf/Chart.yaml
charts/grnoc-telegraf/README.md
charts/grnoc-telegraf/templates/_helpers.tpl
charts/grnoc-telegraf/templates/configmap.yaml
charts/grnoc-telegraf/templates/deployment.yaml
charts/grnoc-telegraf/values.yaml

Closes #44 
See #44 for more info

add grnoc-telegraf content

---

charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/configmap.yaml

Based on https://github.com/slateci/slate-catalog/pull/605/files.

Edited osg-hosted-ce

---

charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/configmap.yaml
charts/osg-hosted-ce/templates/deployment.yaml
charts/osg-hosted-ce/templates/service.yaml

add common labels for the osg-hosted-ce chart

---

charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/networkpolicy.yaml

Add networkpolicy

---

charts/nginx/Chart.yaml

Bumped chart version 1.2.5.

---

charts/globus-connect-v4/Chart.yaml
charts/globus-connect-v4/templates/deployment.yaml

Fixed the image name. Fixes #77

Fix Globus Connect v4 container Image 

---

charts/v4a/Chart.yaml
charts/v4cvmfs/Chart.yaml

Chart version bump for v4* apps.

---

charts/perfsonar-checker/Chart.yaml
charts/perfsonar-checker/templates/configmap.yaml
charts/perfsonar-checker/templates/deployment.yaml

Updated perfsonar-checker chart to use latest base image v4.4.6 and new supervisord configurations for the perfSONAR processes.

Updating perfsonar-checker chart

---

.github/workflows/notify-api.yml
.github/workflows/pr.yaml
.github/workflows/release.yaml

Bumped slateci/github-actions refs to v15.

---

charts/nginx/Chart.yaml
charts/nginx/templates/service.yaml
charts/nginx/values.yaml

Implemented cert manager and tls

116 update nginx app with variable for cert manager cluster issuer

---

.github/workflows/notify-api.yml

Removed dev notification from notify-api.yml.

---

charts/xcache/Chart.yaml
charts/xcache/templates/deployment.yaml
charts/xcache/values.yaml

135 update xcache to use atlas xcache

---

charts/osg-frontier-squid/Chart.yaml
charts/osg-frontier-squid/templates/deployment.yaml
charts/osg-frontier-squid/values.yaml
charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/deployment.yaml
charts/osg-hosted-ce/values.yaml

137 undo pinning versions for osg hosted apps

---

charts/osg-hosted-ce/Chart.yaml
charts/osg-hosted-ce/templates/configmap.yaml

(SOFTWARE-5596)
Also make sure we reference the generated var name in the IDTOKEN name list

Scrub the contents of the user var, not the literal string "$user"
